spring:
  application:
    name: production-service
  config:
    import: optional:configserver:http://localhost:8085

#logging:
#  level:
#    org:
#      hibernate: debug
#      springframework: debug